#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
#production:
#  app: awesomeapp
#  stack: bamboo-ree-1.8.7
#  tag: production/*
#  config:
#    BUNDLE_WITHOUT: "development:test"
#    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  stack: cedar
  app: eurucamp-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
